#!/usr/bin/env bash

rclone bisync GDrive_Work: ~/usr/documents/university/ --drive-skip-dangling-shortcuts --drive-skip-gdocs --drive-skip-shortcuts --filters-file ~/.config/rclone/gdrive_work_filters --log-file ~/.local/share/rclone/logfile.txt
